# Generated by Django 6.0.3 on 2026-04-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='pages',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
