# Generated by Django 6.0.3 on 2026-04-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_updated_at_post_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pages',
            field=models.PositiveIntegerField(),
        ),
    ]
